######################## default configuration ####################
baseURL = "http://localhost:1313/"
languageCode = "fr"
title = "DTF | Derm Tech France"
theme = "Hargo-hugo-ecommerce-theme"
summaryLength = "20"
paginate = 10
disqusShortname = ""

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"


############################## navigation ###############################
[menu]

  [[menu.main]]
  name = "Produits"
  URL = "products"
  weight = 1

  [[menu.main]]
  name = "Pigments / Nuanciers"
  URL = "pigments"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 3

    [[menu.main]]
  name = "À propos"
  URL = "apropos"
  weight = 4

  ############# footer menu #############
  [[menu.footer]]
  name = "Produits"
  URL = "products"
  weight = 1

  [[menu.footer]]
  name = "Pigments / Nuanciers"
  URL = "pigments"
  weight = 2

  [[menu.footer]]
  name = "Conditions générales"
  URL = "conditionsgenerales"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 4

    [[menu.footer]]
  name = "À propos"
  URL = "apropos"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/logo.jpg"
home = "Accueil"
# Meta data
description = "This is meta description"
author = "Themefisher"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "48.827876"
mapLongitude = "2.276595"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# copyright
copyright = "| Copyright &copy; 2021 DTF - Derm Tech France Tout droit réservé |"
# Snipcart Credentials
snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
currencySymbol = "€"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = true
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"



  # Contact Form
  [params.contact]
  formAction = "#" # contact form works with formspree.io

  
